export const SEVIYELER = [
  { seviye: 1, ad: "Meyveler", boyut: 6, kelimeler: ["ELMA", "ARMUT", "MUZ", "KİVİ"] },
   { seviye: 2, ad: "Renkler", boyut: 6, kelimeler: ["SARI", "GRİ", "MAVİ", "SİYAH"] },
   { seviye: 3, ad: "İçecekler", boyut: 6, kelimeler: ["ÇAY", "SU", "SÜT", "AYRAN", "KAHVE"] },
   { seviye: 4, ad: "Yönler", boyut: 6, kelimeler: ["KUZEY", "GÜNEY", "DOĞU", "BATI", "İLERİ"] },
   { seviye: 5, ad: "Aile Bireyleri", boyut: 6, kelimeler: ["ANNE", "BABA", "DAYI", "HALA", "AMCA"] },
   { seviye: 6, ad: "Evin Odaları", boyut: 7, kelimeler: ["SALON", "BANYO", "MUTFAK", "YATAK", "OTURMA", "ANTRE"] },
   { seviye: 7, ad: "Deniz", boyut: 7, kelimeler: ["KUM", "DALGA", "BALIK", "GEMİ", "KÖPÜK", "YOSUN"] },
   { seviye: 8, ad: "Kuşlar", boyut: 7, kelimeler: ["MARTI", "SERÇE", "KARGA", "ŞAHİN", "KARTAL", "DOĞAN", "BAYKUŞ"] },
   { seviye: 9, ad: "Banyo", boyut: 7, kelimeler: ["SABUN", "HAVLU", "KÖPÜK", "ŞAMPUAN", "TARAK", "AYNA", "LİF"] },
   { seviye: 10, ad: "Kamp", boyut: 7, kelimeler: ["ÇADIR", "ATEŞ", "BİDON", "BIÇAK", "FENER", "MATARA", "UYKU"] },
   { seviye: 11, ad: "Orman", boyut: 8, kelimeler: ["AĞAÇ", "YAPRAK", "DAL", "TOPRAK", "ODUN", "KÜTÜK", "TOHUM", "FİDAN"] },
   { seviye: 12, ad: "Hayvanlar", boyut: 8, kelimeler: ["KEDİ", "KÖPEK", "AYI", "KAPLAN", "CEYLAN", "TAVŞAN", "TİLKİ", "KURT"] },
   { seviye: 13, ad: "Taşıtlar", boyut: 8, kelimeler: ["ARABA", "UÇAK", "GEMİ", "TREN", "OTOBÜS", "KAMYON", "VAPUR", "MOTOR"] },
   { seviye: 14, ad: "Meslekler", boyut: 9, kelimeler: ["DOKTOR", "POLİS", "HAKİM", "AŞÇI", "BAKICI", "TERZİ", "KASAP", "BERBER", "MANAV"] },
   { seviye: 15, ad: "Zıt Anlamlar", boyut: 9, kelimeler: ["AÇIK", "KAPALI", "İYİ", "KÖTÜ", "UZUN", "KISA", "AĞIR", "HAFİF", "HIZLI"] },
   { seviye: 16, ad: "Okul Eşyaları", boyut: 9, kelimeler: ["KALEM", "SİLGİ", "DEFTER", "KİTAP", "ÇANTA", "CETVEL", "BOYA", "MAKAS", "PERGEL"] },
   { seviye: 17, ad: "Doğa Olayları", boyut: 10, kelimeler: ["YAĞMUR", "KAR", "DOLU", "SİS", "RÜZGAR", "FIRTINA", "HORTUM", "ŞİMŞEK", "YILDIRIM", "SEL"] },
   { seviye: 18, ad: "Spor Türleri", boyut: 10, kelimeler: ["FUTBOL", "TENİS", "KAYAK", "BOKS", "GÜREŞ", "YÜZME", "HENTBOL", "GOLF", "BİLARDO", "BOWLİNG"] },
   { seviye: 19, ad: "Giysiler", boyut: 10, kelimeler: ["GÖMLEK", "KAZAK", "ETEK", "MONT", "CEKET", "ÇORAP", "ATKI", "ŞAPKA", "HIRKA", "PALTO"] },
   { seviye: 20, ad: "Böcekler", boyut: 11, kelimeler: ["ARI", "SİNEK", "ÖRÜMCEK", "KARINCA", "BİT", "PİRE", "KENE", "KELEBEK", "GÜVE", "BÖCEK", "ÇEKİRGE"] },
   { seviye: 21, ad: "Hastalıklar", boyut: 11, kelimeler: ["ALERJİ", "NEZLE", "GRİP", "BAKTERİ", "VİRÜS", "MİKROP", "VEREM", "ASTIM", "KANSER", "YARA", "AĞRI"] },
   { seviye: 22, ad: "Ev Eşyaları", boyut: 11, kelimeler: ["KOLTUK", "DOLAP", "MASA", "SEHPA", "HALI", "PERDE", "KANEPE", "YATAK", "LAMBA", "SAAT", "TABLO"] },
   { seviye: 23, ad: "Gezegenler", boyut: 12, kelimeler: ["MERKÜR", "VENÜS", "DÜNYA", "MARS", "JÜPİTER", "SATÜRN", "URANÜS", "NEPTÜN", "PLÜTON", "AY", "GÜNEŞ", "YILDIZ"] },
   { seviye: 24, ad: "Kırtasiye", boyut: 12, kelimeler: ["DOSYA", "BANT", "ETİKET", "KLASÖR", "ASETAT", "TUTKAL", "ZIMBA", "ZIMPARA", "DEFTER", "KALEM", "SİLGİ", "ZARF"] },
   { seviye: 25, ad: "Hırdavat", boyut: 12, kelimeler: ["ÇEKİÇ", "ÇİVİ", "VİDA", "SOMUN", "PENSE", "TESTERE", "MATKAP", "KESER", "BALTA", "METRE", "FIRÇA", "RULO"] },
   { seviye: 26, ad: "Müzik Aletleri", boyut: 13, kelimeler: ["GİTAR", "KEMAN", "PİYANO", "SAZ", "KLARNET", "TROMPET", "DAVUL", "FLÜT", "SAKSAFON", "BATERİ", "KANUN", "DARBUKA", "ZİL"] },
   { seviye: 27, ad: "Oyun Türleri", boyut: 13, kelimeler: ["AKSİYON", "MACERA", "SPOR", "YARIŞ", "STRATEJİ", "BULMACA", "KART", "SİMÜLASYON", "ROL", "KUTU", "SAVAŞ", "KELİME", "ZEKA"] },
   { seviye: 28, ad: "Takılar", boyut: 13, kelimeler: ["YÜZÜK", "KÜPE", "KOLYE", "BİLEZİK", "BİLEKLİK", "SAAT", "HALHAL", "BROŞ", "TAÇ", "ROZET", "ZİNCİR", "TOKA", "MADALYON"] },
   { seviye: 29, ad: "Tatil", boyut: 14, kelimeler: ["PLAJ", "KUM", "GÜNEŞ", "DENİZ", "OTEL", "ÇADIR", "GÖZLÜK", "HAVLU", "KREM", "ŞEMSİYE", "VALİZ", "BİLET", "PASAPORT", "SEYAHAT"] },
   { seviye: 30, ad: "Ağaç Türleri", boyut: 14, kelimeler: ["MEŞE", "ÇAM", "İNCİR", "KAYISI", "ELMA", "VİŞNE", "KAVAK", "SÖĞÜT", "CEVİZ", "FINDIK", "BADEM", "ZEYTİN", "HURMA", "LİMON"] },
   { seviye: 31, ad: "Çiçekler", boyut: 14, kelimeler: ["GÜL", "LALE", "PAPATYA", "ZAMBAK", "SÜMBÜL", "MENEKŞE", "SÜSEN", "ORKİDE", "KARANFİL", "NERGİS", "BEGONYA", "KAKTÜS", "İNCİ", "LEYLAK"] },
   { seviye: 32, ad: "Mutfak", boyut: 15, kelimeler: ["TABAK", "ÇATAL", "KAŞIK", "BIÇAK", "TAVA", "TENCERE", "BARDAK", "SÜRAHİ", "CEZVE", "KASE", "RENDE", "SÜZGEÇ", "TEPSİ", "TABLA", "ÇEŞME"] },
   { seviye: 33, ad: "Organlar", boyut: 15, kelimeler: ["GÖZ", "KULAK", "BURUN", "AĞIZ", "DİŞ", "DİL", "KALP", "BEYİN", "MİDE", "KARACİĞER", "BÖBREK", "AKCİĞER", "BAĞIRSAK", "DAMAR", "KEMİK"] },
   { seviye: 34, ad: "Sebzeler", boyut: 15, kelimeler: ["DOMATES", "PATATES", "SOĞAN", "BİBER", "HAVUÇ", "ISPANAK", "PIRASA", "LAHANA", "KABAK", "BAMYA", "TURP", "MARUL", "KEREVİZ", "BROKOLİ", "MANTAR"] },
   { seviye: 35, ad: "Ulaşım", boyut: 15, kelimeler: ["YOLCU", "BİLET", "İSTASYON", "DURAK", "TERMİNAL", "LİMAN", "HAVALİMANI", "PİST", "RAY", "BİLETÇİ", "ŞOFÖR", "PİLOT", "KAPTAN", "HOSTES", "MAKİNİST", "GİŞE"] },
   { seviye: 36, ad: "Kodlama", boyut: 15, kelimeler: ["HTML", "CSS", "JAVASCRIPT", "REACT", "VUE", "ANGULAR", "NODE", "PYTHON", "JAVA", "RUBY", "PHP", "MYSQL", "MONGO", "REDIS", "SWIFT", "KOTLİN"] },
   { seviye: 37, ad: "Bilgisayar", boyut: 15, kelimeler: ["EKRAN", "KLAVYE", "FARE", "İŞLEMCİ", "BELLEK", "DİSK", "KASA", "FAN", "ANAKART", "MONİTÖR", "KAMERA", "YAZICI", "MODEM", "KABLO", "HOPARLÖR", "VİRÜS"] },
   { seviye: 38, ad: "Anadolu Şehirleri", boyut: 15, kelimeler: ["İSTANBUL", "ANKARA", "İZMİR", "BURSA", "ADANA", "ANTALYA", "KONYA", "TRABZON", "SAMSUN", "BURDUR", "RİZE", "SİNOP", "MUĞLA", "HATAY", "TOKAT", "SİVAS", "VAN"] },
   { seviye: 39, ad: "Hisler", boyut: 15, kelimeler: ["MUTLU", "ÜZGÜN", "KIZGIN", "ŞAŞKIN", "KORKMUŞ", "HEYECAN", "ENDİŞE", "SİNİR", "NEŞE", "HUZUR", "GURUR", "CESUR", "UTANGAÇ", "SAKİN", "AŞK", "SEVGİ", "NEFRET"] },
   { seviye: 40, ad: "Meyveler 2", boyut: 15, kelimeler: ["KARPUZ", "KAVUN", "ŞEFTALİ", "KİRAZ", "VİŞNE", "ERİK", "KAYISI", "DUT", "İNCİR", "NAR", "AYVA", "MANDALİNA", "PORTAKAL", "GREYFURT", "LİMON", "ÇİLEK", "ELMA"] },
   { seviye: 41, ad: "Uzay Bilimi", boyut: 15, kelimeler: ["GALAKSİ", "EVREN", "KOZMOZ", "YILDIZ", "ASTEROİT", "METEOR", "YÖRÜNGE", "KARADELİK", "BULUTSU", "UYDU", "ROKET", "ASTRONOT", "KAPSÜL", "GÖKTAŞI", "TUTULMA", "YERÇEKİMİ", "TELESKOP", "BOŞLUK"] },
   { seviye: 42, ad: "Ülkeler", boyut: 15, kelimeler: ["TÜRKİYE", "ALMANYA", "FRANSA", "İTALYA", "İSPANYA", "JAPONYA", "BREZİLYA", "KANADA", "RUSYA", "ÇİN", "HİNDİSTAN", "MISIR", "MEKSİKA", "KORE", "İSVEÇ", "NORVEÇ", "DANİMARKA", "İRLANDA"] },
   { seviye: 43, ad: "Tarih", boyut: 15, kelimeler: ["SAVAŞ", "BARIŞ", "ANTLAŞMA", "İMPARATOR", "KRAL", "VEZİR", "PADİŞAH", "SADRAZAM", "PAŞA", "MİMAR", "ASKER", "SİLAH", "KILIÇ", "KALKAN", "OK", "YAY", "ZAFER", "BOZGUN"] },
   { seviye: 44, ad: "Matematik", boyut: 15, kelimeler: ["RAKAM", "SAYI", "TOPLAMA", "ÇIKARMA", "ÇARPMA", "BÖLME", "KESİR", "YÜZDE", "AÇI", "DERECE", "EŞİTLİK", "DENKLEM", "TÜREV", "İNTEGRAL", "LİMİT", "MATRİS", "GEOMETRİ", "CEBİR", "MANTIK"] },
   { seviye: 45, ad: "Geometri", boyut: 15, kelimeler: ["KARE", "ÜÇGEN", "DAİRE", "DİKDÖRTGEN", "BEŞGEN", "ALTIGEN", "SİLİNDİR", "KÜRE", "KONİ", "PRİZMA", "PİRAMİT", "SEKİZGEN", "YEDİGEN", "ELİPS", "YILDIZ", "YAMUK", "EŞKENAR", "NOKTA", "DOĞRU"] },
   { seviye: 46, ad: "Sinema", boyut: 15, kelimeler: ["AKTÖR", "AKTRİS", "YÖNETMEN", "SENARYO", "KAMERA", "SAHNE", "VİZYON", "FİLM", "DUBLAJ", "MONTAJ", "GİŞE", "REPLİK", "KURGU", "KOSTÜM", "MAKYAJ", "DEKOR", "YAPIMCI", "IŞIK", "SET"] },
   { seviye: 47, ad: "Mitoloji", boyut: 15, kelimeler: ["ZEUS", "HERA", "POSEİDON", "ARES", "HERMES", "APOLLON", "ARTEMİS", "AFRODİT", "ATHENA", "DİONYSOS", "EROS", "TİTAN", "KENTAUR", "MEDUSA", "PEGASUS", "OLİMPOS", "SİREN", "PERİ", "KAHRAMAN", "DESTAN"] },
   { seviye: 48, ad: "Avrupa Şehirleri", boyut: 15, kelimeler: ["LONDRA", "PARİS", "ROMA", "BERLİN", "MADRİD", "VİYANA", "PRAG", "AMSTERDAM", "ATİNA", "BUDAPEŞTE", "LİZBON", "VARŞOVA", "OSLO", "STOCKHOLM", "MOSKOVA", "KİEV", "BRÜKSEL", "DUBLİN", "ZÜRİH", "MİLANO"] },
   { seviye: 49, ad: "Spor Etkinlikleri", boyut: 15, kelimeler: ["FUTBOL", "BASKETBOL", "VOLEYBOL", "TENİS", "YÜZME", "GÜREŞ", "HENTBOL", "BOKS", "ATLETİZM", "OKÇULUK", "KAYAK", "BİSİKLET", "JİMNASTİK", "HALTER", "JUDO", "KARATE", "TEKVANDO", "ESKRİM", "SATRANÇ", "BİLARDO"] },
   { seviye: 50, ad: "Büyük Final", boyut: 15, kelimeler: ["ŞAMPİYON", "EFSANE", "BAŞARI", "ZAFER", "KUTLAMA", "ÖDÜL", "KUPA", "MADALYA", "FİNAL", "BİRİNCİ", "HARİKA", "MÜKEMMEL", "SÜPER", "ZİRVE", "UNVAN", "ALKIŞ", "GURUR", "TEBRİK", "HEYECAN", "SONUÇ"] }
];
